name: DisplayHearts
main: net.ddns.vcccd.Main
version: 1.0
api-version: 1.20
commands:
   #iwannafly:
      #description: Your description
      #usage: /<command>
      #permission: yourplugin.yourcmission
